### ISSUE TITLE
Improve exception handling and reporting

### ISSUE THREAD

**Issue by arnikz** [PBR/QTM#50]
Re-running QTM on the same input raises the following exception:

```
...
Insert entry to the database.
-------------------------------------------------
java.sql.SQLException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: ARTICLE.pmc_id)
	at org.sqlite.core.DB.newSQLException(DB.java:890)
	at org.sqlite.core.DB.newSQLException(DB.java:901)
	at org.sqlite.core.DB.execute(DB.java:810)
	at org.sqlite.core.DB.executeUpdate(DB.java:847)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:86)
	at resultDb.QtlDb.insertArticleEntry(QtlDb.java:132)
	at qtm.QtmMain.main(QtmMain.java:128)
*************************************************
Article already exits, Please provide unique entries
*************************************************
```
A user should be notified as soon as possible rather than waiting for this message after processing input articles.

**Comment by arnikz** [comment]
Is it really needed to process beyond article? Checking for PMCID should suffice, I think. Image if you have hundreds of articles; a user will have to wait to finish processing QTLs.

The warning message could be improved (use logging level WARNING), for example:

`WARNING: The article with [PMCID] has already been processed. Skip.`

```
NUMBER OF QTL TABLESSS:3
1		true
2		true
3		true


Restarting Solr.
---------------------------------------------
...
QTL detected is not Unique. Already exiting: log (TA)
...
```
